# Site settings
title: Sympheny | Orchestrating local energy solutions
description: "Leveraging intelligent analytics & big data to support the development of sustainable energy solutions at local scale."
url: "http://www.sympheny.com/"
author:
  name: "Julien Marquant"
  email: "sympheny.energy@gmail.com"
  url: "http://www.sympheny.com/"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
